[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_BUILD_DEBUG = "true"
  NEXT_PUBLIC_BACKEND_URL = "https://r4s.onrender.com"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 30
  max_payload = "15mb"
