-- Connect to roadsintel database first
USE roadsintel;

-- Create RoadImage table
CREATE TABLE IF NOT EXISTS RoadImage (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  filename VARCHAR(191) NOT NULL,
  path VARCHAR(191) NOT NULL,
  uploadedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  status VARCHAR(191) NOT NULL DEFAULT 'pending',
  crackCount INT NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create CrackDetection table
CREATE TABLE IF NOT EXISTS CrackDetection (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  imageId VARCHAR(191) NOT NULL,
  boxes TEXT NULL,
  crackCount INT NOT NULL,
  confidence DOUBLE NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX CrackDetection_imageId_idx (imageId),
  FOREIGN KEY (imageId) REFERENCES RoadImage(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create WorkOrder table
CREATE TABLE IF NOT EXISTS WorkOrder (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  imageId VARCHAR(191) NOT NULL,
  crackCount INT NOT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'Open',
  priority INT NOT NULL DEFAULT 0,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX WorkOrder_imageId_idx (imageId),
  INDEX WorkOrder_status_idx (status),
  FOREIGN KEY (imageId) REFERENCES RoadImage(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

